libKOS.o: libKOS.cc \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/ulib/../testoptions.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/ulib/../include/syscalls.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/ulib/../include/kostypes.h
pthread.o: pthread.cc \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/ulib/../testoptions.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/ulib/../include/syscalls.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/ulib/../include/kostypes.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/ulib/../include/pthread.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/ulib/../include/syscalls.h
