threadtest.o: threadtest.cc \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../testoptions.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../include/syscalls.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../include/kostypes.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../include/pthread.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../include/syscalls.h
systest.o: systest.cc \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../testoptions.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../include/syscalls.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../include/kostypes.h
manythread.o: manythread.cc \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../testoptions.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../include/syscalls.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../include/kostypes.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../include/pthread.h \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../include/syscalls.h
kbloop.o: kbloop.cc \
 /home/ugd/bbajic/Assignment3_New/Assign3/src/src/user/../testoptions.h
